export * from './chartAPI.service';
import { ChartAPIService } from './chartAPI.service';
export * from './JWTUserAPI.service';
import { JWTUserAPIService } from './JWTUserAPI.service';
export * from './pageAPI.service';
import { PageAPIService } from './pageAPI.service';
export * from './productAPI.service';
import { ProductAPIService } from './productAPI.service';
export * from './sellerAPI.service';
import { SellerAPIService } from './sellerAPI.service';
export * from './transactionAPI.service';
import { TransactionAPIService } from './transactionAPI.service';
export const APIS = [ChartAPIService, JWTUserAPIService, PageAPIService, ProductAPIService, SellerAPIService, TransactionAPIService];
